- name: Open zabbix-agent port
  ansible.posix.firewalld:
    port: "{{ zabbix_agent_firewalld_port }}"
    state: enabled
    immediate: true
    permanent: true

- name: Making sure semanage is available on system
  ansible.builtin.dnf:
    name:
      - policycoreutils-python-utils
      - checkpolicy
    state: present
    update_cache: true

- name: Allow zabbix agents ports in SELinux
  community.general.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: zabbix_port_t
    state: present
  loop: "{{ zabbix_SELinux_ports }}"

- name: Create system directory for all SELinux-related files
  ansible.builtin.file:
    path: /etc/selinux/local
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy SELinux text file on to machines
  ansible.builtin.copy:
    src: zabbix_agent_local.te
    dest: /etc/selinux/local
    mode: '0644'
  register: te_file

- name: Check if zabbix_agent_local is in SEmodule list on system
  ansible.builtin.shell: |
    semodule -l | grep zabbix_agent_local
  register: zabbix_se
  ignore_errors: true
  changed_when: false

- name: Compile and integrate SELinux rules for zabbix
  ansible.builtin.shell: |
    checkmodule -M -m -o /etc/selinux/local/zabbix_agent_local.mod /etc/selinux/local/zabbix_agent_local.te
    semodule_package -o /etc/selinux/local/zabbix_agent_local.pp -m /etc/selinux/local/zabbix_agent_local.mod
    semodule -i /etc/selinux/local/zabbix_agent_local.pp
  when: >
    te_file.changed or
    "'zabbix_agent_local' not in zabbix_se.stdout"

- name: Copy SELinux text file on to machines
  ansible.builtin.copy:
    src: zabbix_agent2_local.te
    dest: /etc/selinux/local
    mode: '0644'
  register: te_file2

- name: Check if zabbix_agent2_local is in SEmodule list on system
  ansible.builtin.shell: |
    semodule -l | grep zabbix_agent2_local
  register: zabbix2_se
  ignore_errors: true
  changed_when: false

- name: Compile and integrate SELinux rules for zabbix one more time
  ansible.builtin.shell: |
    checkmodule -M -m -o /etc/selinux/local/zabbix_agent2_local.mod /etc/selinux/local/zabbix_agent2_local.te
    semodule_package -o /etc/selinux/local/zabbix_agent2_local.pp -m /etc/selinux/local/zabbix_agent2_local.mod
    semodule -i /etc/selinux/local/zabbix_agent2_local.pp
  when: >
    te_file2.changed or
    "'zabbix_agent2_local' not in zabbix2_se.stdout"

- name: Import GPG-Key
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-B5333005

- name: Enable CRB repository for dependencies
  ansible.builtin.shell: dnf config-manager --set-enabled crb

- name: Install epel-release if not installed (Like on minimal AlmaLinux 9)
  ansible.builtin.dnf:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm'
    state: present
    disable_gpg_check: true

- name: Remove release Zabbix package
  ansible.builtin.dnf:
    name: zabbix-release
    state: absent

- name: Install release Zabbix package
  ansible.builtin.dnf:
    name: 'https://repo.zabbix.com/zabbix/7.0/alma/9/x86_64/zabbix-release-latest-7.0.el9.noarch.rpm'
    state: present

- name: Clear dnf cache for system to re-read package lists
  ansible.builtin.shell: dnf clean all

- name: Disable Zabbix packages provided by EPEL (if exists)
  community.general.ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: excludepkgs
    value: zabbix*
    state: present

- name: Install Zabbix-agent
  ansible.builtin.dnf:
    name:
      - zabbix-agent
    state: present

- name: Use agent config file from template
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: '0644'
  notify: Restart zabbix-agent
